// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace API_Clinica.Models
{
    public partial class usp_Medico_Espec_ConvenioChatResult
    {
        public int ID_Medico { get; set; }
        public long? Codigo { get; set; }
        public string NM_Medico { get; set; }
        public int ID_Convenio { get; set; }
    }
}
