// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace API_Clinica.Models
{
    public partial class usp_Lista_PacienteChatResult
    {
        public int ID_Paciente { get; set; }
        public string NM_Paciente { get; set; }
        public DateTime? DT_Nascto { get; set; }
        public string NR_Celular { get; set; }
    }
}
