// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace API_Clinica.Models
{
    public partial class usp_Separar_Consulta_AgendaChatResult
    {
        public long? Ordem { get; set; }
        public int? ID_Consulta { get; set; }
        public string DT_Consulta { get; set; }
        public string Nome { get; set; }
        public string Situacao { get; set; }
        public string Especialidade { get; set; }
        public string HS_Consulta { get; set; }
    }
}
