// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace API_Clinica.Models
{
    public partial class VwEspecialidadeConvenioChat
    {
        public int IdConvenio { get; set; }
        public string NmConvenio { get; set; }
        public long? Codigo { get; set; }
        public string Especialidade { get; set; }
        public int IdEspecialidade { get; set; }
        public string NmEspecialidade { get; set; }
    }
}